import{$,$$,getTheme,setTheme,openEmail,revealOnScroll}from'../Helper/siteHelper.js';
export class SiteViewModel{
 init(){setTheme(getTheme());this.theme();this.menu();this.year();this.mailLinks();this.forms();revealOnScroll()}
 theme(){const b=$('#themeToggle');if(!b)return;const u=()=>{const d=document.documentElement.dataset.theme==='dark';b.innerHTML='<span class="themeIcon" aria-hidden="true">'+(d?'☀':'☾')+'</span>';b.setAttribute('aria-label',d?'Switch to light theme':'Switch to dark theme');b.title=d?'Switch to light theme':'Switch to dark theme'};b.addEventListener('click',()=>{setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');u()});u()}
 menu(){const b=$('#menuToggle'),n=$('#mainNav');if(!b||!n)return;const close=()=>{n.classList.remove('is-open');b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Open navigation menu')};b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const open=!n.classList.contains('is-open');n.classList.toggle('is-open',open);b.setAttribute('aria-expanded',String(open));b.setAttribute('aria-label',open?'Close navigation menu':'Open navigation menu')});n.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('click',e=>{if(!n.contains(e.target)&&!b.contains(e.target))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});window.addEventListener('resize',()=>{if(window.innerWidth>900)close()})}
 year(){const y=$('#year');if(y)y.textContent=new Date().getFullYear()}
 mailLinks(){$$('[data-mail-subject]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openEmail(a.dataset.mailSubject||'Website enquiry')}))}
 forms(){$$('form[data-demo-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();if(!f.checkValidity()){f.reportValidity();return}const data=new FormData(f);openEmail(data.get('subject')||'Website enquiry','Name: '+data.get('name')+'\nEmail: '+data.get('email')+'\n\n'+data.get('message'))}))}
}
document.addEventListener('DOMContentLoaded',()=>new SiteViewModel().init(),{once:true});