import{$,$$,getTheme,setTheme,revealOnScroll}from'../Helper/siteHelper.js';

export class SiteViewModel{
 init(){setTheme(getTheme());this.theme();this.menu();this.year();this.forms();revealOnScroll()}
 theme(){const b=$('#themeToggle');if(!b)return;const u=()=>{const d=document.documentElement.dataset.theme==='dark';b.textContent=d?'☀':'◐';b.setAttribute('aria-label',d?'Switch to light theme':'Switch to dark theme')};b.addEventListener('click',()=>{setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');u()});u()}
 menu(){const b=$('#menuToggle'),n=$('#mainNav');if(!b||!n)return;const close=()=>{n.classList.remove('is-open');b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Open navigation menu')};b.addEventListener('click',e=>{e.stopPropagation();const o=!n.classList.contains('is-open');n.classList.toggle('is-open',o);b.setAttribute('aria-expanded',String(o));b.setAttribute('aria-label',o?'Close navigation menu':'Open navigation menu')});n.addEventListener('click',e=>e.stopPropagation());document.addEventListener('click',close);$('#mainNav a').forEach(a=>a.addEventListener('click',close));window.addEventListener('resize',()=>{if(window.innerWidth>900)close()})}
 year(){const y=$('#year');if(y)y.textContent=new Date().getFullYear()}
 forms(){$$('form[data-demo-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();if(!f.checkValidity()){f.reportValidity();return}const data=new FormData(f);const subject=encodeURIComponent(data.get('subject')||'Website enquiry');const body=encodeURIComponent('Name: '+data.get('name')+'\nEmail: '+data.get('email')+'\n\n'+data.get('message'));window.location.href='mailto:hindtechgroup@gmail.com?subject='+subject+'&body='+body}))}
}
document.addEventListener('DOMContentLoaded',()=>new SiteViewModel().init());